import { Currency } from '../types/Currency';

export const currencies: Currency[] = [
  { abbreviation: 'AED', symbol: 'د.إ', name: 'United Arab Emirates Dirham' },
  { abbreviation: 'AFN', symbol: '؋', name: 'Afghan Afghani' },
  { abbreviation: 'ALL', symbol: 'L', name: 'Albanian Lek' },
  { abbreviation: 'AMD', symbol: '֏', name: 'Armenian Dram' },
  { abbreviation: 'ANG', symbol: 'ƒ', name: 'Netherlands Antillean Guilder' },
  { abbreviation: 'AOA', symbol: 'Kz', name: 'Angolan Kwanza' },
  { abbreviation: 'ARS', symbol: '$', name: 'Argentine Peso' },
  { abbreviation: 'AUD', symbol: '$', name: 'Australian Dollar' },
  { abbreviation: 'AWG', symbol: 'ƒ', name: 'Aruban Florin' },
  { abbreviation: 'AZN', symbol: '₼', name: 'Azerbaijani Manat' },
  {
    abbreviation: 'BAM',
    symbol: 'KM',
    name: 'Bosnia-Herzegovina Convertible Mark',
  },
  { abbreviation: 'BBD', symbol: '$', name: 'Barbadian Dollar' },
  { abbreviation: 'BDT', symbol: '৳', name: 'Bangladeshi Taka' },
  { abbreviation: 'BGN', symbol: 'лв', name: 'Bulgarian Lev' },
  { abbreviation: 'BHD', symbol: 'ب.د', name: 'Bahraini Dinar' },
  { abbreviation: 'BIF', symbol: 'FBu', name: 'Burundian Franc' },
  { abbreviation: 'BMD', symbol: '$', name: 'Bermudan Dollar' },
  { abbreviation: 'BND', symbol: '$', name: 'Brunei Dollar' },
  { abbreviation: 'BOB', symbol: 'Bs.', name: 'Bolivian Boliviano' },
  { abbreviation: 'BRL', symbol: 'R$', name: 'Brazilian Real' },
  { abbreviation: 'BSD', symbol: '$', name: 'Bahamian Dollar' },
  { abbreviation: 'BTC', symbol: '₿', name: 'Bitcoin' },
  { abbreviation: 'BTN', symbol: 'Nu.', name: 'Bhutanese Ngultrum' },
  { abbreviation: 'BWP', symbol: 'P', name: 'Botswanan Pula' },
  { abbreviation: 'BYN', symbol: 'Br', name: 'Belarusian Ruble' },
  { abbreviation: 'BZD', symbol: 'BZ$', name: 'Belize Dollar' },
  { abbreviation: 'CAD', symbol: '$', name: 'Canadian Dollar' },
  { abbreviation: 'CDF', symbol: 'FC', name: 'Congolese Franc' },
  { abbreviation: 'CHF', symbol: 'Fr.', name: 'Swiss Franc' },
  { abbreviation: 'CLF', symbol: 'UF', name: 'Chilean Unit of Account (UF)' },
  { abbreviation: 'CLP', symbol: '$', name: 'Chilean Peso' },
  { abbreviation: 'CNH', symbol: '¥', name: 'Chinese Yuan (offshore)' },
  { abbreviation: 'CNY', symbol: '¥', name: 'Chinese Yuan' },
  { abbreviation: 'COP', symbol: '$', name: 'Colombian Peso' },
  { abbreviation: 'CRC', symbol: '₡', name: 'Costa Rican Colón' },
  { abbreviation: 'CUC', symbol: '$', name: 'Cuban Convertible Peso' },
  { abbreviation: 'CUP', symbol: '₱', name: 'Cuban Peso' },
  { abbreviation: 'CVE', symbol: 'Esc', name: 'Cape Verdean Escudo' },
  { abbreviation: 'CZK', symbol: 'Kč', name: 'Czech Koruna' },
  { abbreviation: 'DJF', symbol: 'Fdj', name: 'Djiboutian Franc' },
  { abbreviation: 'DKK', symbol: 'kr.', name: 'Danish Krone' },
  { abbreviation: 'DOP', symbol: 'RD$', name: 'Dominican Peso' },
  { abbreviation: 'DZD', symbol: 'د.ج', name: 'Algerian Dinar' },
  { abbreviation: 'EGP', symbol: 'ج.م', name: 'Egyptian Pound' },
  { abbreviation: 'ERN', symbol: 'Nfk', name: 'Eritrean Nakfa' },
  { abbreviation: 'ETB', symbol: 'Br', name: 'Ethiopian Birr' },
  { abbreviation: 'EUR', symbol: '€', name: 'Euro' },
  { abbreviation: 'FJD', symbol: '$', name: 'Fijian Dollar' },
  { abbreviation: 'FKP', symbol: '£', name: 'Falkland Islands Pound' },
  { abbreviation: 'GBP', symbol: '£', name: 'British Pound Sterling' },
  { abbreviation: 'GEL', symbol: '₾', name: 'Georgian Lari' },
  { abbreviation: 'GGP', symbol: '£', name: 'Guernsey Pound' },
  { abbreviation: 'GHS', symbol: '₵', name: 'Ghanaian Cedi' },
  { abbreviation: 'GIP', symbol: '£', name: 'Gibraltar Pound' },
  { abbreviation: 'GMD', symbol: 'D', name: 'Gambian Dalasi' },
  { abbreviation: 'GNF', symbol: 'FG', name: 'Guinean Franc' },
  { abbreviation: 'GTQ', symbol: 'Q', name: 'Guatemalan Quetzal' },
  { abbreviation: 'GYD', symbol: '$', name: 'Guyanaese Dollar' },
  { abbreviation: 'HKD', symbol: '$', name: 'Hong Kong Dollar' },
  { abbreviation: 'HNL', symbol: 'L', name: 'Honduran Lempira' },
  { abbreviation: 'HRK', symbol: 'kn', name: 'Croatian Kuna' },
  { abbreviation: 'HTG', symbol: 'G', name: 'Haitian Gourde' },
  { abbreviation: 'HUF', symbol: 'Ft', name: 'Hungarian Forint' },
  { abbreviation: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah' },
  { abbreviation: 'ILS', symbol: '₪', name: 'Israeli New Shekel' },
  { abbreviation: 'IMP', symbol: '£', name: 'Isle of Man Pound' },
  { abbreviation: 'INR', symbol: '₹', name: 'Indian Rupee' },
  { abbreviation: 'IQD', symbol: 'ع.د', name: 'Iraqi Dinar' },
  { abbreviation: 'IRR', symbol: '﷼', name: 'Iranian Rial' },
  { abbreviation: 'ISK', symbol: 'kr', name: 'Icelandic Króna' },
  { abbreviation: 'JEP', symbol: '£', name: 'Jersey Pound' },
  { abbreviation: 'JMD', symbol: 'J$', name: 'Jamaican Dollar' },
  { abbreviation: 'JOD', symbol: 'د.ا', name: 'Jordanian Dinar' },
  { abbreviation: 'JPY', symbol: '¥', name: 'Japanese Yen' },
  { abbreviation: 'KES', symbol: 'Ksh', name: 'Kenyan Shilling' },
  { abbreviation: 'KGS', symbol: 'с', name: 'Kyrgystani Som' },
  { abbreviation: 'KHR', symbol: '៛', name: 'Cambodian Riel' },
  { abbreviation: 'KMF', symbol: 'CF', name: 'Comorian Franc' },
  { abbreviation: 'KPW', symbol: '₩', name: 'North Korean Won' },
  { abbreviation: 'KRW', symbol: '₩', name: 'South Korean Won' },
  { abbreviation: 'KWD', symbol: 'د.ك', name: 'Kuwaiti Dinar' },
  { abbreviation: 'KYD', symbol: '$', name: 'Cayman Islands Dollar' },
  { abbreviation: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge' },
  { abbreviation: 'LAK', symbol: '₭', name: 'Laotian Kip' },
  { abbreviation: 'LBP', symbol: 'ل.ل', name: 'Lebanese Pound' },
  { abbreviation: 'LKR', symbol: '₨', name: 'Sri Lankan Rupee' },
  { abbreviation: 'LRD', symbol: '$', name: 'Liberian Dollar' },
  { abbreviation: 'LSL', symbol: 'M', name: 'Lesotho Loti' },
  { abbreviation: 'LYD', symbol: 'ل.د', name: 'Libyan Dinar' },
  { abbreviation: 'MAD', symbol: 'د.م.', name: 'Moroccan Dirham' },
  { abbreviation: 'MDL', symbol: 'L', name: 'Moldovan Leu' },
  { abbreviation: 'MGA', symbol: 'Ar', name: 'Malagasy Ariary' },
  { abbreviation: 'MKD', symbol: 'ден', name: 'Macedonian Denar' },
  { abbreviation: 'MMK', symbol: 'K', name: 'Myanma Kyat' },
  { abbreviation: 'MNT', symbol: '₮', name: 'Mongolian Tugrik' },
  { abbreviation: 'MOP', symbol: 'P', name: 'Macanese Pataca' },
  { abbreviation: 'MRU', symbol: 'UM', name: 'Mauritanian Ouguiya' },
  { abbreviation: 'MUR', symbol: '₨', name: 'Mauritian Rupee' },
  { abbreviation: 'MVR', symbol: 'Rf', name: 'Maldivian Rufiyaa' },
  { abbreviation: 'MWK', symbol: 'MK', name: 'Malawian Kwacha' },
  { abbreviation: 'MXN', symbol: '$', name: 'Mexican Peso' },
  { abbreviation: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit' },
  { abbreviation: 'MZN', symbol: 'MT', name: 'Mozambican Metical' },
  { abbreviation: 'NAD', symbol: '$', name: 'Namibian Dollar' },
  { abbreviation: 'NGN', symbol: '₦', name: 'Nigerian Naira' },
  { abbreviation: 'NIO', symbol: 'C$', name: 'Nicaraguan Córdoba' },
  { abbreviation: 'NOK', symbol: 'kr', name: 'Norwegian Krone' },
  { abbreviation: 'NPR', symbol: '₨', name: 'Nepalese Rupee' },
  { abbreviation: 'NZD', symbol: '$', name: 'New Zealand Dollar' },
  { abbreviation: 'OMR', symbol: 'ر.ع.', name: 'Omani Rial' },
  { abbreviation: 'PAB', symbol: 'B/.', name: 'Panamanian Balboa' },
  { abbreviation: 'PEN', symbol: 'S/.', name: 'Peruvian Sol' },
  { abbreviation: 'PGK', symbol: 'K', name: 'Papua New Guinean Kina' },
  { abbreviation: 'PHP', symbol: '₱', name: 'Philippine Peso' },
  { abbreviation: 'PKR', symbol: '₨', name: 'Pakistani Rupee' },
  { abbreviation: 'PLN', symbol: 'zł', name: 'Polish Złoty' },
  { abbreviation: 'PYG', symbol: '₲', name: 'Paraguayan Guarani' },
  { abbreviation: 'QAR', symbol: 'ر.ق', name: 'Qatari Rial' },
  { abbreviation: 'RON', symbol: 'lei', name: 'Romanian Leu' },
  { abbreviation: 'RSD', symbol: 'дин', name: 'Serbian Dinar' },
  { abbreviation: 'RUB', symbol: '₽', name: 'Russian Ruble' },
  { abbreviation: 'RWF', symbol: 'RF', name: 'Rwandan Franc' },
  { abbreviation: 'SAR', symbol: 'ر.س', name: 'Saudi Riyal' },
  { abbreviation: 'SBD', symbol: '$', name: 'Solomon Islands Dollar' },
  { abbreviation: 'SCR', symbol: '₨', name: 'Seychellois Rupee' },
  { abbreviation: 'SDG', symbol: 'ج.س.', name: 'Sudanese Pound' },
  { abbreviation: 'SEK', symbol: 'kr', name: 'Swedish Krona' },
  { abbreviation: 'SGD', symbol: '$', name: 'Singapore Dollar' },
  { abbreviation: 'SHP', symbol: '£', name: 'Saint Helena Pound' },
  { abbreviation: 'SLL', symbol: 'Le', name: 'Sierra Leonean Leone' },
  { abbreviation: 'SOS', symbol: 'Sh', name: 'Somali Shilling' },
  { abbreviation: 'SRD', symbol: '$', name: 'Surinamese Dollar' },
  { abbreviation: 'SSP', symbol: '£', name: 'South Sudanese Pound' },
  { abbreviation: 'STD', symbol: 'Db', name: 'São Tomé and Príncipe Dobra' },
  { abbreviation: 'STN', symbol: 'Db', name: 'São Tomé and Príncipe Dobra' },
  { abbreviation: 'SVC', symbol: '$', name: 'Salvadoran Colón' },
  { abbreviation: 'SYP', symbol: '£', name: 'Syrian Pound' },
  { abbreviation: 'SZL', symbol: 'E', name: 'Swazi Lilangeni' },
  { abbreviation: 'THB', symbol: '฿', name: 'Thai Baht' },
  { abbreviation: 'TJS', symbol: 'SM', name: 'Tajikistani Somoni' },
  { abbreviation: 'TMT', symbol: 'T', name: 'Turkmenistan Manat' },
  { abbreviation: 'TND', symbol: 'د.ت', name: 'Tunisian Dinar' },
  { abbreviation: 'TOP', symbol: 'T$', name: 'Tongan Paʻanga' },
  { abbreviation: 'TRY', symbol: '₺', name: 'Turkish Lira' },
  { abbreviation: 'TTD', symbol: 'TT$', name: 'Trinidad and Tobago Dollar' },
  { abbreviation: 'TWD', symbol: 'NT$', name: 'New Taiwan Dollar' },
  { abbreviation: 'TZS', symbol: 'Sh', name: 'Tanzanian Shilling' },
  { abbreviation: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia' },
  { abbreviation: 'UGX', symbol: 'USh', name: 'Ugandan Shilling' },
  { abbreviation: 'USD', symbol: '$', name: 'United States Dollar' },
  { abbreviation: 'UYU', symbol: '$', name: 'Uruguayan Peso' },
  { abbreviation: 'UZS', symbol: 'лв', name: 'Uzbekistani Som' },
  { abbreviation: 'VES', symbol: 'Bs.', name: 'Venezuelan Bolívar Soberano' },
  { abbreviation: 'VND', symbol: '₫', name: 'Vietnamese Đồng' },
  { abbreviation: 'VUV', symbol: 'Vt', name: 'Vanuatu Vatu' },
  { abbreviation: 'WST', symbol: 'T', name: 'Samoan Tala' },
  { abbreviation: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc' },
  { abbreviation: 'XAG', symbol: 'oz t', name: 'Silver (troy ounce)' },
  { abbreviation: 'XAU', symbol: 'oz t', name: 'Gold (troy ounce)' },
  { abbreviation: 'XCD', symbol: '$', name: 'East Caribbean Dollar' },
  { abbreviation: 'XDR', symbol: 'SDR', name: 'Special Drawing Rights' },
  { abbreviation: 'XOF', symbol: 'CFA', name: 'West African CFA Franc' },
  { abbreviation: 'XPD', symbol: 'oz t', name: 'Palladium (troy ounce)' },
  { abbreviation: 'XPF', symbol: '₣', name: 'CFP Franc' },
  { abbreviation: 'XPT', symbol: 'oz t', name: 'Platinum (troy ounce)' },
  { abbreviation: 'YER', symbol: '﷼', name: 'Yemeni Rial' },
  { abbreviation: 'ZAR', symbol: 'R', name: 'South African Rand' },
  { abbreviation: 'ZMW', symbol: 'ZK', name: 'Zambian Kwacha' },
  { abbreviation: 'ZWL', symbol: '$', name: 'Zimbabwean Dollar' },
];
